POST http://127.0.0.1:5000/option-pricing/black-scholes/
Content-Type: application/json

{
  "S": 100,
  "K": 110,
  "T": 1,
  "r": 0.05,
  "sigma": 0.2,
  "option_type": "call" }

### POST request to analyze WTI-Brent spread
POST http://127.0.0.1:5000/option-pricing/spread-analysis
Content-Type: application/json

{
  "wti_price": 75.5,
  "brent_price": 80.3
}

### Another request with different values
POST http://127.0.0.1:5000/option-pricing/spread-analysis
Content-Type: application/json

{
  "wti_price": 74.2,
  "brent_price": 81.0
}



